function fuelCheck()
    while(turtle.getFuelLevel() < 100) do
        turtle.select(5)
        turtle.refuel(1)
    end
end

while true do
    turtle.forward()
    turtle.forward()

    for dig15=1,15 do
        turtle.turnRight()
        turtle.dig()
        turtle.suck()
        turtle.suckDown()
        turtle.select(1)
        turtle.place()
        turtle.turnLeft()
        turtle.turnLeft()
        turtle.dig()
        turtle.suck()
        turtle.suckDown()
        turtle.select(2)
        turtle.place()
        turtle.turnRight()
        turtle.forward()
        fuelCheck()
    end

    fuelCheck()
    turtle.turnLeft()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.turnLeft()
    turtle.forward()

    for dig15=1,15 do
        turtle.turnRight()
        turtle.dig()
        turtle.suck()
        turtle.suckDown()
        turtle.select(2)
        turtle.place()
        turtle.turnLeft()
        turtle.turnLeft()
        turtle.dig()
        turtle.suck()
        turtle.suckDown()
        turtle.select(2)
        turtle.place()
        turtle.turnRight()
        turtle.forward()
        fuelCheck()
    end

    fuelCheck()
    turtle.turnRight()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.turnRight()
    turtle.forward()

    for dig15=1,15 do
        turtle.turnRight()
        turtle.dig()
        turtle.suck()
        turtle.suckDown()
        turtle.select(2)
        turtle.place()
        turtle.turnLeft()
        turtle.turnLeft()
        turtle.dig()
        turtle.suck()
        turtle.suckDown()
        turtle.select(3)
        turtle.place()
        turtle.turnRight()
        turtle.forward()
        fuelCheck()
    end

    fuelCheck()
    turtle.turnLeft()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.turnLeft()
    turtle.forward()

    for dig15=1,15 do
        turtle.turnRight()
        turtle.dig()
        turtle.suck()
        turtle.suckDown()
        turtle.select(3)
        turtle.place()
        turtle.turnLeft()
        turtle.turnLeft()
        turtle.dig()
        turtle.suck()
        turtle.suckDown()
        turtle.select(3)
        turtle.place()
        turtle.turnRight()
        turtle.forward()
        fuelCheck()
    end

    fuelCheck()
    turtle.turnRight()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.turnRight()
    turtle.forward()

    for dig15=1,15 do
        turtle.turnRight()
        turtle.dig()
        turtle.suck()
        turtle.suckDown()
        turtle.select(3)
        turtle.place()
        turtle.turnLeft()
        turtle.turnLeft()
        turtle.dig()
        turtle.suck()
        turtle.suckDown()
        turtle.select(4)
        turtle.place()
        turtle.turnRight()
        turtle.forward()
        fuelCheck()
    end

    turtle.turnRight()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()

    turtle.turnRight()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.forward()
    turtle.turnRight()
    turtle.turnRight()

    function dropItems()
        for dropSlot=5,16 do
            turtle.select(dropSlot)
            turtle.dropDown()
        end
        turtle.select(1)
    end

    dropItems()
    turtle.suckDown()
    turtle.suckDown()
    turtle.suckDown()
    turtle.suckDown()
    turtle.suckDown()
    turtle.suckDown()
    turtle.suckDown()
    turtle.suckDown()
    turtle.suckDown()
    turtle.suckDown()
    turtle.suckDown()
    turtle.suckDown()
    dropItems()

    sleep(1860)
end